require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.5.7
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120

