cli_wallet_connection: ws://localhost:8099
registrar_account: your_faucet_account
voting_account: your_voting_account
referrer_percent: 50
refcode_prefix: F01

mattermost_hook: 123
mattermost_username: stage
mattermost_channel: alerts

default_url: localhost
default_port: 3000

exception_notification:
  sender_address: faucet@example.com
  exception_recipients: admin@example.com

smtp:
  address: address
  user_name: user
  password: password
